INHERIT: website-template/mkdocs.yml

docs_dir: 'docs'

repo_name: Ansible Playbooks
repo_url: https://gitlab.com/nofusscomputing/projects/ansible/ansible_playbooks
edit_uri: '/-/ide/project/nofusscomputing/projects/ansible/ansible_playbooks/edit/development/-/docs/'

nav:
- Home: index.md

- Articles: 

  - articles/index.md

- Projects: 

  - projects/index.md

  - Ansible:

    - projects/ansible/index.md

    - Playbooks: 

      - projects/ansible/playbooks/index.md

      - projects/ansible/playbooks/awx.md

      - Backup: 
      
        - projects/ansible/playbooks/backup/index.md

        - projects/ansible/playbooks/backup/application.md

      - projects/ansible/playbooks/common.md

      - projects/ansible/playbooks/git_configuration.md

      - projects/ansible/playbooks/glpi.md

      - projects/ansible/playbooks/keycloak.md

      - projects/ansible/playbooks/mariadb.md

      - projects/ansible/playbooks/postgresdb.md

      - Restoration:
      
        - projects/ansible/playbooks/restore/index.md

        - projects/ansible/playbooks/restore/application.md

    - Roles:

      - projects/ansible/roles/index.md

      - common:

        - projects/ansible/roles/common/index.md

- Operations: 

  - operations/index.md

- Contact Us: contact.md

